name: 2019 msbuild

on: push

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Debug

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '16.0'

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Run executable
      run: |
         Write-Host "Find and test"
         $dllPath = Get-ChildItem -Path "x64\Debug" -Filter "*.dll" -Recurse | Select-Object -First 1 -ExpandProperty FullName
         if ($dllPath) {
            Write-Host "Test container found: $dllPath"
            & vstest.console.exe dllPath
         } else {
           Write-Host "No test container dll found."
         }
